name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libpq-dev

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Install pandas and Airflow manually
      run: |
        source venv/bin/activate
        pip install pandas==1.5.3 apache-airflow==2.10.1

    - name: Run Tests with Unittest
      run: |
        source venv/bin/activate
        python -m unittest discover tests/
